name: MineSkyCustom
version: 1.0.0-RELEASE
main: net.mineskycustom.MineSkyCustom

api-version: 26.1

folia-supported: true

softdepend:
  - "MythicMobs"
  - "ProtocolLib"
  - "mainframe"
  - "WorldEdit"
  - "WorldGuard"
  - "Geyser-Spigot"

commands:
  cb:
    aliases:
      - "customblocks"
  mscustom:
    aliases:
      - "mineskycustom"